const books = [
  {
    id: "1",
    title: "Atomic Habits",
    author: "James Clear",
    year: 2018,
    description: "A practical guide to building good habits, breaking bad ones, and mastering tiny behaviors for remarkable results.",
    image: "/books/atomic-habits.png",
  },
  {
    id: "2",
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    year: 1989,
    description: "Timeless principles for personal and professional effectiveness, focusing on proactive habits and values.",
    image: "",
  },
  {
    id: "3",
    title: "Deep Work",
    author: "Cal Newport",
    year: 2016,
    description: "Explores the ability to focus without distraction in a noisy world and how it leads to extraordinary productivity.",
    image: "",
  },
  {
    id: "4",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    year: 1997,
    description: "A spiritual guide to living fully in the present moment and freeing yourself from mental distractions.",
    image: "",
  },
  {
    id: "5",
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    year: 1937,
    description: "Classic motivational book that reveals timeless principles for success, wealth, and achievement.",
    image: "",
  },
  {
    id: "6",
    title: "Can't Hurt Me",
    author: "David Goggins",
    year: 2018,
    description: "The story of Navy SEAL David Goggins, focusing on mental toughness, discipline, and pushing beyond limits.",
    image: "",
  },
  {
    id: "7",
    title: "Make Your Bed",
    author: "Admiral William H. McRaven",
    year: 2017,
    description: "Life lessons from a Navy SEAL, starting with small daily habits that can change your life and the world.",
    image: "",
  },
  {
    id: "8",
    title: "The Miracle Morning",
    author: "Hal Elrod",
    year: 2012,
    description: "A morning routine framework (SAVERS) to maximize productivity, happiness, and personal growth.",
    image: "",
  },
  {
    id: "9",
    title: "Essentialism: The Disciplined Pursuit of Less",
    author: "Greg McKeown",
    year: 2014,
    description: "A guide to focusing on what truly matters, eliminating non-essential tasks, and simplifying life.",
    image: "",
  },
  {
    id: "10",
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    year: 2016,
    description: "A counterintuitive approach to living a good life by focusing only on what truly matters.",
    image: "",
  },
];


export default books
